/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;
import java.util.Scanner;
import java.io.File;
import java.io.FileNotFoundException;
import heap.Heap;
import avl.AVL;

public class Huffman {
    public static void main(String[] args) {
        Scanner sc;

        try{
            sc = new Scanner(new File(args[0]));
        } catch (FileNotFoundException e){
            e.printStackTrace();
            return;
        }
        Heap<String, Integer> h = countFrequencies(sc);
    }
    
    
    public static Heap<String, Integer> countFrequencies(Scanner input){
        while(input.hasNextLine()){
            String line = input.nextLine();
            for(int i = 0; i < line.length(); i++){
                System.out.print(line.charAt(i));
            }
            System.out.println("");
        }
        return null;
    }
}
