/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;
import java.util.Scanner;
import java.io.File;
import java.io.FileNotFoundException;
import heap.Heap;
import avl.AVL;

public class Huffman {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner sc;

        try{
            sc = new Scanner(new File(args[0]));
        } catch (FileNotFoundException e){
            e.printStackTrace();
            return;
        }
    }
}
